### ISSUE TITLE
list-card

### ISSUE THREAD

**Issue by iantrich** [iantrich/hass#40]
A generic list card, much like the beer-card but you define the columns and their display headers

e.g.
```
Preacher 3x09 "Schwanzkopf"
{ "published": "Sun, Aug 19 09:00 PM", "title": "Preacher 3x09 \"Schwanzkopf\"", "summary": "Divided and trapped, Tulip, Jesse and Cassidy battle old friends, new enemies and loved ones to escape certain death - or worse.", "media_content": [ { "url": "https://walter.trakt.tv/images/shows/000/102/034/posters/medium/71b370c005.jpg" } ], "media_thumbnail": [ { "url": "https://walter.trakt.tv/images/shows/000/102/034/posters/thumb/71b370c005.jpg" } ] }
```

```
- type: custom:list-card
  entity: trakt_upcoming
  title: Upcoming Shows
  columns:
    - field: media_thumbnail
      type: image
    - name: Air Date
      field: published
    - name: Show
      field: title
    - name: Synopsis
      field: summary
```

Supported column types: `image` default is `string`
